services:
  lbd_production:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_ENV: production
        NEXT_PUBLIC_API_URL: https://api.lbd.rgbindia.com
    container_name: lbd_production
    env_file: .env.production
    ports:
      - "3100:3000"
      - "4100:4000"
    restart: unless-stopped

  lbd_staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_ENV: staging
        NEXT_PUBLIC_API_URL: https://api.lbd-staging.rgbindia.com
    container_name: lbd_staging
    env_file: .env.staging
    ports:
      - "3101:3000"
      - "4101:4000"
    restart: unless-stopped
